<a href="https://colab.research.google.com/github/MarthatiVignesh/pandas-data-cleaning/blob/main/data_cleaning_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

In [8]:
from google.colab import files

uploaded = files.upload()

Saving basic-data.csv to basic-data (2).csv

In [11]:
df = pd.read_csv("basic-data (2).csv")

In [12]:
df.head()

,# This sample CSV file is provided by Sample-Files.com. Visit us for more sample files and resources.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ID,Name,Age,Country,Email
1,1,Name_1,62,Country_1,email_1@example.com
2,2,Name_2,0,Country_2,email_2@example.com
3,3,NaN,61,Country_3,email_3@example.com
4,4,Name_4,32,Country_4,email_4@example.com

In [15]:
df = pd.read_csv("basic-data (2).csv", skiprows=1)

In [16]:
df.columns

Index(['ID', 'Name', 'Age', 'Country', 'Email'], dtype='object')

In [17]:
df["Age"].value_counts().sort_index()

Age
0     6
18    2
19    3
20    1
21    2
24    2
25    1
26    1
28    4
30    1
31    4
32    6
33    3
34    1
35    3
36    1
38    3
39    3
40    3
41    1
43    3
44    2
45    2
46    2
47    2
49    1
50    3
51    1
52    2
53    1
54    1
55    3
58    1
59    1
60    3
61    3
62    3
63    1
66    4
67    2
68    5
69    3
Name: count, dtype: int64

In [18]:
df[df["Age"] == 0]

    ID     Name  Age    Country                 Email
1    2   Name_2    0  Country_2   email_2@example.com
6    7   Name_7    0  Country_7   email_7@example.com
15  16  Name_16    0  Country_6  email_16@example.com
26  27  Name_27    0  Country_7  email_27@example.com
33  34  Name_34    0  Country_4  email_34@example.com
38  39  Name_39    0  Country_9                   NaN

In [19]:
(df["Age"] == 0).sum()

np.int64(6)

In [20]:
median_age = df.loc[df["Age"] > 0, "Age"].median()

print(median_age)

43.0

In [21]:
df.loc[df["Age"] == 0, "Age"] = median_age

In [22]:
(df["Age"] == 0).sum()

np.int64(0)

In [23]:
df["Email"].isna().sum()

np.int64(4)

In [24]:
df["Email"] = df["Email"].fillna("test@example.com")

In [25]:
df["Email"].isna().sum()

np.int64(0)

In [26]:
df["Name"].isna().sum()

np.int64(3)

In [27]:
df["Name"] = df["Name"].fillna("default")

In [28]:
df["Name"].isna().sum()

np.int64(0)

In [29]:
df.isna().sum()

ID         0
Name       0
Age        0
Country    0
Email      0
dtype: int64

In [30]:
df.to_csv("cleaned_basic_data.csv", index=False)

In [31]:
print("Data cleaning completed successfully!")
print("File saved as: cleaned_basic_data.csv")

Data cleaning completed successfully!
File saved as: cleaned_basic_data.csv

In [32]:
from google.colab import files

files.download("cleaned_basic_data.csv")